server {
    listen 80;
    server_name mindgate.futumore.pl;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name mindgate.futumore.pl;

    ssl_certificate     /etc/letsencrypt/live/mindgate.futumore.pl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mindgate.futumore.pl/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        resolver 127.0.0.11 valid=30s;
        set $mindgate http://mindgate-gate:3000;
        proxy_pass $mindgate;

        proxy_connect_timeout 5s;
        proxy_read_timeout    300s;
        proxy_send_timeout    300s;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # SSE / streaming
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
        chunked_transfer_encoding on;
    }

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }
}
