server {
    listen 80;
    server_name nextouch.futumore.pl;

    location / {
        return 301 https://$host$request_uri;
    }

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }
}

server {
    listen 443 ssl;
    server_name nextouch.futumore.pl;

    ssl_certificate     /etc/letsencrypt/live/nextouch.futumore.pl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nextouch.futumore.pl/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Frontend (static files)
    location / {
        resolver 127.0.0.11 valid=30s;
        set $nextouch_frontend http://nextouch-frontend:80;
        proxy_pass $nextouch_frontend;

        proxy_connect_timeout 5s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend API
    location /api/ {
        resolver 127.0.0.11 valid=30s;
        set $nextouch_backend http://nextouch-backend:3000;
        proxy_pass $nextouch_backend;

        proxy_connect_timeout 5s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Important for webhooks
        proxy_buffering off;
    }

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }
}
